/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchdogRouteImport } from './routes/watchdog'
import { Route as VitalRouteImport } from './routes/vital'
import { Route as TimeRouteImport } from './routes/time'
import { Route as RssRouteImport } from './routes/rss'
import { Route as FlashcardRouteImport } from './routes/flashcard'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as ExporterRouteImport } from './routes/exporter'
import { Route as DrawRouteImport } from './routes/draw'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AnyiconRouteImport } from './routes/anyicon'
import { Route as AnyfanaRouteImport } from './routes/anyfana'
import { Route as IndexRouteImport } from './routes/index'

const WatchdogRoute = WatchdogRouteImport.update({
  id: '/watchdog',
  path: '/watchdog',
  getParentRoute: () => rootRouteImport,
} as any)
const VitalRoute = VitalRouteImport.update({
  id: '/vital',
  path: '/vital',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeRoute = TimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => rootRouteImport,
} as any)
const RssRoute = RssRouteImport.update({
  id: '/rss',
  path: '/rss',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardRoute = FlashcardRouteImport.update({
  id: '/flashcard',
  path: '/flashcard',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ExporterRoute = ExporterRouteImport.update({
  id: '/exporter',
  path: '/exporter',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawRoute = DrawRouteImport.update({
  id: '/draw',
  path: '/draw',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnyiconRoute = AnyiconRouteImport.update({
  id: '/anyicon',
  path: '/anyicon',
  getParentRoute: () => rootRouteImport,
} as any)
const AnyfanaRoute = AnyfanaRouteImport.update({
  id: '/anyfana',
  path: '/anyfana',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anyfana': typeof AnyfanaRoute
  '/anyicon': typeof AnyiconRoute
  '/calendar': typeof CalendarRoute
  '/draw': typeof DrawRoute
  '/exporter': typeof ExporterRoute
  '/finance': typeof FinanceRoute
  '/flashcard': typeof FlashcardRoute
  '/rss': typeof RssRoute
  '/time': typeof TimeRoute
  '/vital': typeof VitalRoute
  '/watchdog': typeof WatchdogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anyfana': typeof AnyfanaRoute
  '/anyicon': typeof AnyiconRoute
  '/calendar': typeof CalendarRoute
  '/draw': typeof DrawRoute
  '/exporter': typeof ExporterRoute
  '/finance': typeof FinanceRoute
  '/flashcard': typeof FlashcardRoute
  '/rss': typeof RssRoute
  '/time': typeof TimeRoute
  '/vital': typeof VitalRoute
  '/watchdog': typeof WatchdogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anyfana': typeof AnyfanaRoute
  '/anyicon': typeof AnyiconRoute
  '/calendar': typeof CalendarRoute
  '/draw': typeof DrawRoute
  '/exporter': typeof ExporterRoute
  '/finance': typeof FinanceRoute
  '/flashcard': typeof FlashcardRoute
  '/rss': typeof RssRoute
  '/time': typeof TimeRoute
  '/vital': typeof VitalRoute
  '/watchdog': typeof WatchdogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anyfana'
    | '/anyicon'
    | '/calendar'
    | '/draw'
    | '/exporter'
    | '/finance'
    | '/flashcard'
    | '/rss'
    | '/time'
    | '/vital'
    | '/watchdog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anyfana'
    | '/anyicon'
    | '/calendar'
    | '/draw'
    | '/exporter'
    | '/finance'
    | '/flashcard'
    | '/rss'
    | '/time'
    | '/vital'
    | '/watchdog'
  id:
    | '__root__'
    | '/'
    | '/anyfana'
    | '/anyicon'
    | '/calendar'
    | '/draw'
    | '/exporter'
    | '/finance'
    | '/flashcard'
    | '/rss'
    | '/time'
    | '/vital'
    | '/watchdog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnyfanaRoute: typeof AnyfanaRoute
  AnyiconRoute: typeof AnyiconRoute
  CalendarRoute: typeof CalendarRoute
  DrawRoute: typeof DrawRoute
  ExporterRoute: typeof ExporterRoute
  FinanceRoute: typeof FinanceRoute
  FlashcardRoute: typeof FlashcardRoute
  RssRoute: typeof RssRoute
  TimeRoute: typeof TimeRoute
  VitalRoute: typeof VitalRoute
  WatchdogRoute: typeof WatchdogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchdog': {
      id: '/watchdog'
      path: '/watchdog'
      fullPath: '/watchdog'
      preLoaderRoute: typeof WatchdogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vital': {
      id: '/vital'
      path: '/vital'
      fullPath: '/vital'
      preLoaderRoute: typeof VitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time': {
      id: '/time'
      path: '/time'
      fullPath: '/time'
      preLoaderRoute: typeof TimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss': {
      id: '/rss'
      path: '/rss'
      fullPath: '/rss'
      preLoaderRoute: typeof RssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcard': {
      id: '/flashcard'
      path: '/flashcard'
      fullPath: '/flashcard'
      preLoaderRoute: typeof FlashcardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exporter': {
      id: '/exporter'
      path: '/exporter'
      fullPath: '/exporter'
      preLoaderRoute: typeof ExporterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draw': {
      id: '/draw'
      path: '/draw'
      fullPath: '/draw'
      preLoaderRoute: typeof DrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anyicon': {
      id: '/anyicon'
      path: '/anyicon'
      fullPath: '/anyicon'
      preLoaderRoute: typeof AnyiconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anyfana': {
      id: '/anyfana'
      path: '/anyfana'
      fullPath: '/anyfana'
      preLoaderRoute: typeof AnyfanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnyfanaRoute: AnyfanaRoute,
  AnyiconRoute: AnyiconRoute,
  CalendarRoute: CalendarRoute,
  DrawRoute: DrawRoute,
  ExporterRoute: ExporterRoute,
  FinanceRoute: FinanceRoute,
  FlashcardRoute: FlashcardRoute,
  RssRoute: RssRoute,
  TimeRoute: TimeRoute,
  VitalRoute: VitalRoute,
  WatchdogRoute: WatchdogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
